name: binder-env
channels:
  - conda-forge
dependencies:
  - python=3.12
  - notebook
  - ipykernel
  - matplotlib
  - ipympl
  - ipywidgets
  - numpy
  - pandas
  - scipy
  - seaborn
  - lmfit
  - jupyterlab
  - nbformat
  - nbconvert
  - pip:
    - jupyterlab-language-pack-fr-FR
    - jupyterlab-spreadsheet-editor
